-- Scraper / rewrite rules на уровне feed; кэш полного контента в entries.

ALTER TABLE feeds
  ADD COLUMN IF NOT EXISTS scraper_rules TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS rewrite_rules TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS blocked_rules TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS keep_rules TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS fetch_via_proxy BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS crawler BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS user_agent TEXT NOT NULL DEFAULT '';

ALTER TABLE entries
  ADD COLUMN IF NOT EXISTS original_content TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS content_fetched BOOLEAN NOT NULL DEFAULT FALSE;
